### ISSUE TITLE
Remove ability to configure ngx-conf using configuration files

### ISSUE THREAD

**Issue by Lekensteyn** [ngx/ngx-conf#7]
Most of the options should not be hidden away in a conf file which is inconsistent across invocations (for example, `--force`). The only variable that you probably want to change is the base dir, be it for a chroot configuration or testing purposes.

An overview of keys:

| Key | Default value | Comment |
| --- | --- | --- |
| base_dir | /etc/nginx/ | Use envvar `NGINX_CONFDIR`? |
| conf_dir | conf.d/ | Remove customization, assume default |
| sites_en | sites-enabled/ | Remove customization, assume default |
| sites_dis | sites-available/ | Remove customization, assume default |
| conf_ext | .conf | ??? |
| verbose | no | Use command line option |
| reload | no | Use command line option (do not hide!) |
| force | no | Use command line option (do not hide!) |

Hard-coding the defaults allow for a standard. The intended audience are users who do not want to know the details, so for them we should decide on the standard location which works with nginx.conf. Others can create symlinks themselves.

As for `conf_ext`... that is a different issue.

**Comment by MTecknology** [comment]
I have to disagree with this. I realize the chances someone would mess with this are incredibly low, but I strongly prefer leaving it open. Adding the ability to modify one thing vs. many things is insanely trivial. Perhaps some should be removed, but not all.

**Comment by MTecknology** [comment]
Closing because a lack of activity.
